# Generated by Django 5.0.1 on 2024-01-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название графика')),
                ('image', models.ImageField(upload_to='charts/', verbose_name='График')),
                ('dict', models.JSONField(null=True, verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'График востребованности',
                'verbose_name_plural': 'Графики востребованности',
            },
        ),
        migrations.CreateModel(
            name='GeoChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название графика')),
                ('image', models.ImageField(upload_to='charts/', verbose_name='График')),
                ('dict', models.JSONField(null=True, verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'График географии',
                'verbose_name_plural': 'Графики географии',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название профессии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='pictures/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('dict', models.JSONField(null=True, verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Ключевой навык',
                'verbose_name_plural': 'Ключевые навыки',
            },
        ),
    ]
